<a href="https://colab.research.google.com/github/regiiis/station_itinarary_mapping/blob/main/itinerary_mapping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

#connect to drive
import os
from google.colab import drive
drive.mount('/content/drive')

#set up for reading google sheets
from google.colab import auth
import gspread
from google.auth import default

auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)

Mounted at /content/drive

In [2]:
#load data into pd df
worksheet = gc.open('fahrplan_winter_17_10_2022').sheet1
rows = worksheet.get_all_values()
fahr_p = pd.DataFrame(rows)
fahr_p.columns = fahr_p.iloc[0]
fahr_p = fahr_p[1:] #implizit crop first row

freq = pd.read_csv('/content/drive/My Drive/Colab Notebooks/geo_data/People frequency_month_stations_SGV.csv', encoding= 'unicode_escape', sep=';')

In [3]:
#display fahrplan

fahr_p

,Kursnummer,401,1,403,7,407,11,13,15,415,21,23,25,425,27,427,29,33
1,Luzern Bahnhofquai,,x,,x,,x,x,x,,x,x,x,,x,,x,x
2,Verkehrshaus-Lido,,,,x,,x,x,x,,,x,x,,x,,,
3,Hertenstein,,,,x,,x,x,x,,,x,x,,x,,x,x
4,Weggis,,x,,x,,x,x,x,,,x,x,,x,,x,x
5,Vitznau,,,,x,,x,x,x,x,x,x,x,,x,,,x
6,Beckenried,,,,x,x,x,,,x,,x,x,x,x,,,
7,Gersau,,,,,x,x,,,x,,,,x,,,,
8,Treib,x,,x,,x,x,,,x,,,,x,,x,,
9,Brunnen,x,,x,,x,x,,,x,,,,x,,x,,
10,Rütli,,,x,,x,x,,,x,,,,,,,,
11,Sisikon,,,,,,,,,,,,,,,,,
12,Tellsplatte,,,,,,,,,x,,,,,,,,
13,Bauen,,,,,,x,,,x,,,,,,,,
14,Isleten-Isenthal,,,,,,x,,,,,,,,,,,
15,Flüelen,,,,,,x,,,x,,,,,,,,
16,Luzern Bahnhofquai,,,,,,x,,,x,,,,,,,,

In [8]:
#query: passenger frequency by 'Course number'

freq[freq['Course number'].str.contains("24")]

,Station,Course number,IN / OUT,Total,January,February,March,April,May,June,July,August,September,October,November,December,Percent,Rang,Change to 2020
24,Bauen,13_24,IN,3.820,-,-,-,-,580,901,440,738,858,303,-,-,NaN,NaN,NaN
25,Bauen,13_24,OUT,640,-,-,-,-,78,158,112,144,107,41,-,-,NaN,NaN,NaN
48,Bauen,413_424,IN,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,NaN,NaN
49,Bauen,413_424,OUT,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,NaN,NaN
72,Beckenried,13_24,IN,11.016,-,-,-,-,1.519,2.064,1.297,2.030,2.984,1.122,-,-,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1335,Vitznau,23_24,OUT,5.552,376,615,639,1.387,-,-,-,-,-,847,746,942,NaN,NaN,NaN
1402,Weggis,13_24,IN,18.046,-,-,-,-,2.554,3.384,1.981,3.566,4.545,2.016,-,-,NaN,NaN,NaN
1403,Weggis,13_24,OUT,17.406,-,-,-,-,2.430,3.362,2.212,3.447,4.188,1.767,-,-,NaN,NaN,NaN
1418,Weggis,23_24,IN,8.083,509,1.096,853,2.104,-,-,-,-,-,1.458,957,1.106,NaN,NaN,NaN
1419,Weggis,23_24,OUT,8.731,618,1.203,1.386,2.565,-,-,-,-,-,1.242,877,840,NaN,NaN,NaN

In [9]:
#get list of unique course number
#input [df]: sort_values('Course number')
#output [array]: course_nr

course_nr = freq.sort_values('Course number')
course_nr = course_nr['Course number'].unique()
course_nr

array(['101', '1026', '1027_28', '106', '107', '108', '109', '110',
       '1107', '111', '11_20', '12', '13_14', '13_24', '14', '151_152',
       '153_154', '155_156', '15_16', '17', '17_26', '18', '1_4', '205',
       '207', '209', '211', '213', '21_18', '21_30', '23', '23_24',
       '23_32', '25', '25_26', '25_28', '27', '27_30', '29_38', '301_302',
       '303_304', '305_306', '307_308', '33_36', '35', '35_40', '402_401',
       '404_403', '405', '405_410', '407_414', '408_405', '410',
       '410_407', '413_424', '421', '422', '423', '424', '424_423', '425',
       '426', '427', '430', '430_427', '432', '434', '43_44', '45_46',
       '51_52', '55_56', '57_58', '5_14', '614', '616', '61_62', '630',
       '631', '632', '633', '634', '635', '636', '63_64', '640', '65_66',
       '676', '681', '682', '683', '691', '692', '693', '695', '696',
       '697', '699', '69_70', '701', '702', '703', '704', '705', '7_10',
       '7_18', '8', '811_812', '901', '902', '903', '904', '905', '906',
       '907', '908', '909', '910', '911', '912', '913', '914', '915',
       '9_10', 'BD_17_26', 'EXTRA 1', 'EXTRA 2', 'EXTRA 3', 'EXTRA 5',
       'EXTRA 6', 'EXTRA4', 'Total Frequenz', 'Total IN', 'Total OUT'],
      dtype=object)

#**Step 1: Create Base DF**

In [10]:
#create df with columns: "course_nr", "station", "previous_stat", "next_stat", "IN", "OUT"
#input : course_nr, freq
#output: itinerary

it_df = pd.DataFrame(columns =["course_nr", "station", "previous_stat", "next_stat"])

for i in course_nr:
  for m, n in freq.iterrows():
    if i == n[1]:
      empty = pd.DataFrame(columns =["course_nr", "station", "previous_stat", "next_stat"])
      empty.append([""])
      empty.at[0, ["course_nr", "station"]] = n[1], n[0]
      empty.at[0, [n[2]]] = n[3]
      it_df = it_df.append(empty, ignore_index = True)

#group df by course number and station, in order t merge IN and OUT into one row
from numpy import NaN
itinerary_df = it_df.groupby(['course_nr', 'station']).sum()
itinerary = itinerary_df.drop(columns = NaN, axis=1)

itinerary

                              previous_stat  next_stat     IN      OUT
course_nr station
101       Luzern Bahnhofquai              0          0  2.522    2.083
          Verkehrshaus-Lido               0          0     10      449
1026      Hertenstein                     0          0     19        3
          Luzern Bahnhofquai              0          0   -         164
          Verkehrshaus-Lido               0          0     16        2
...                                     ...        ...    ...      ...
Total OUT Tribschen                       0          0      0    1.225
          Verkehrshaus-Lido               0          0      0   72.335
          Vitznau                         0          0      0  163.877
          Vitznau Park                    0          0      0      268
          Weggis                          0          0      0  133.257

[779 rows x 4 columns]

In [11]:
#clean the cloumn; correct the bad data ('IN','OUT'; numbers are e0 and e3)

itinerary = itinerary_df.drop(columns = NaN, axis=1)

itinerary['previous_stat'] = ""
itinerary['next_stat'] = ""

itinerary['IN'] = itinerary['IN'].str.replace('-','0')
itinerary['OUT'] = itinerary['OUT'].str.replace('-','0')

itinerary['IN'] = [float(x['IN']) * 1000 if float(x['IN']) % 1 != 0 else x['IN'] for i, x in itinerary.iterrows()] # * 1000 if residuals
itinerary['OUT'] = [float(x['OUT']) * 1000 if float(x['OUT']) % 1 != 0 else x['OUT'] for i, x in itinerary.iterrows()]


itinerary

                             previous_stat next_stat      IN       OUT
course_nr station
101       Luzern Bahnhofquai                          2522.0    2083.0
          Verkehrshaus-Lido                               10       449
1026      Hertenstein                                     19         3
          Luzern Bahnhofquai                            0          164
          Verkehrshaus-Lido                               16         2
...                                    ...       ...     ...       ...
Total OUT Tribschen                                      NaN    1225.0
          Verkehrshaus-Lido                              NaN   72335.0
          Vitznau                                        NaN  163877.0
          Vitznau Park                                   NaN       268
          Weggis                                         NaN  133257.0

[779 rows x 4 columns]

#**Step 2: Reduce Dimensionality**

In [12]:
#reduce dimensionality of fahrplan for convenient looping
fahrplan = pd.melt(fahr_p, id_vars=['Kursnummer'], var_name = 'course_nr', value_name = 'halt', value_vars=['401', '7',	'407',	'11',	'13',	'15',	'415',	'21',	'23',	'25',	'425',	'27',	'427',	'29',	'33', '1', '403'], ignore_index=False)
fahrplan.rename(columns={'Kursnummer':'station'}, inplace=True)
fahrplan

               station course_nr halt
1   Luzern Bahnhofquai       401
2    Verkehrshaus-Lido       401
3          Hertenstein       401
4               Weggis       401
5              Vitznau       401
..                 ...       ...  ...
12         Tellsplatte       403
13               Bauen       403
14    Isleten-Isenthal       403
15             Flüelen       403
16  Luzern Bahnhofquai       403

[272 rows x 3 columns]

#**Step 3: Map "previous station" and "next station" in Base DF**

In [14]:
#map station with previous station and next station

"""
itinerary:
i = index
r = course_nr, station, previous_stat, next_stat, total, IN, OUT

fahrplan:
n = index
m = station, course_nr, halt
"""

for i in course_nr:
  if fahrplan[(fahrplan['course_nr'] == i) & (fahrplan['halt'] == 'x')].empty == False:
    subset = (fahrplan[(fahrplan['course_nr'] == i) & (fahrplan['halt'] == 'x')])
    subset.reset_index(inplace = True)
    length = len(subset)
    print(subset)
    print(f'\nlength: {length}')
    for n, r in subset.iterrows():
      print(f'index: {n}\n')
      print(f'Station: {r["station"]}\n')

      if n == 0:
        print('Is First Station')
        itinerary.at[(str(r['course_nr']), r['station']),'previous_stat'] = "start"  #access cell value df.at[row, column]
      else:
        itinerary.at[(str(r['course_nr']), r['station']),'previous_stat'] = subset['station'][(n-1)]
        print("Previous Station: ", subset['station'][(n-1)])

      if n+1 == length:
        print('Is Last Station')
        itinerary.at[(str(r['course_nr']), r['station']),'next_stat'] = "end"
      else:
        print(f'Next Station: {subset["station"][(n+1)]}')
        itinerary.at[(r['course_nr'], r['station']),'next_stat'] = subset['station'][(n+1)]

      print('END\n')

   index             station course_nr halt
0      1  Luzern Bahnhofquai        23    x
1      2   Verkehrshaus-Lido        23    x
2      3         Hertenstein        23    x
3      4              Weggis        23    x
4      5             Vitznau        23    x
5      6          Beckenried        23    x

length: 6
index: 0

Station: Luzern Bahnhofquai

Is First Station
Next Station: Verkehrshaus-Lido
END

index: 1

Station: Verkehrshaus-Lido

Previous Station:  Luzern Bahnhofquai
Next Station: Hertenstein
END

index: 2

Station: Hertenstein

Previous Station:  Verkehrshaus-Lido
Next Station: Weggis
END

index: 3

Station: Weggis

Previous Station:  Hertenstein
Next Station: Vitznau
END

index: 4

Station: Vitznau

Previous Station:  Weggis
Next Station: Beckenried
END

index: 5

Station: Beckenried

Previous Station:  Vitznau
Is Last Station
END

   index             station course_nr halt
0      1  Luzern Bahnhofquai        25    x
1      2   Verkehrshaus-Lido        25    x
2      3         Hertenstein        25    x
3      4              Weggis        25    x
4      5             Vitznau        25    x
5      6          Beckenried        25    x

length: 6
index: 0

Station: Luzern Bahnhofquai

Is First Station
Next Station: Verkehrshaus-Lido
END

index: 1

Station: Verkehrshaus-Lido

Previous Station:  Luzern Bahnhofquai
Next Station: Hertenstein
END

index: 2

Station: Hertenstein

Previous Station:  Verkehrshaus-Lido
Next Station: Weggis
END

index: 3

Station: Weggis

Previous Station:  Hertenstein
Next Station: Vitznau
END

index: 4

Station: Vitznau

Previous Station:  Weggis
Next Station: Beckenried
END

index: 5

Station: Beckenried

Previous Station:  Vitznau
Is Last Station
END

   index             station course_nr halt
0      1  Luzern Bahnhofquai        27    x
1      2   Verkehrshaus-Lido        27    x
2      3         Hertenstein        27    x
3      4              Weggis        27    x
4      5             Vitznau        27    x
5      6          Beckenried        27    x

length: 6
index: 0

Station: Luzern Bahnhofquai

Is First Station
Next Station: Verkehrshaus-Lido
END

index: 1

Station: Verkehrshaus-Lido

Previous Station:  Luzern Bahnhofquai
Next Station: Hertenstein
END

index: 2

Station: Hertenstein

Previous Station:  Verkehrshaus-Lido
Next Station: Weggis
END

index: 3

Station: Weggis

Previous Station:  Hertenstein
Next Station: Vitznau
END

index: 4

Station: Vitznau

Previous Station:  Weggis
Next Station: Beckenried
END

index: 5

Station: Beckenried

Previous Station:  Vitznau
Is Last Station
END

   index     station course_nr halt
0      6  Beckenried       425    x
1      7      Gersau       425    x
2      8       Treib       425    x
3      9     Brunnen       425    x

length: 4
index: 0

Station: Beckenried

Is First Station
Next Station: Gersau
END

index: 1

Station: Gersau

Previous Station:  Beckenried
Next Station: Treib
END

index: 2

Station: Treib

Previous Station:  Gersau
Next Station: Brunnen
END

index: 3

Station: Brunnen

Previous Station:  Treib
Is Last Station
END

   index  station course_nr halt
0      8    Treib       427    x
1      9  Brunnen       427    x

length: 2
index: 0

Station: Treib

Is First Station
Next Station: Brunnen
END

index: 1

Station: Brunnen

Previous Station:  Treib
Is Last Station
END

#**Step 4: Map coordinates of station and next station**

In [15]:
#load station coordinates into pd df

coord = pd.read_excel('/content/drive/My Drive/Colab Notebooks/geo_data/koordinaten.xlsx')
coord

                  Station       Long       Lat
0   Kehrsiten-Bürgenstock  47.003022  8.382353
1      Luzern Bahnhofquai  47.051305  8.310240
2             Alpnachstad  46.955808  8.278793
3                   Bauen  46.935272  8.580444
4              Beckenried  46.967170  8.475421
5                 Brunnen  46.993338  8.605265
6                  Buochs  46.970373  8.593285
7             Ennetbürgen  46.988055  8.421072
8                 Flüelen  46.903360  8.624594
9                 Greppen  47.056178  8.426862
10                 Gersau  46.990769  8.526075
11            Hertenstein  47.026916  8.403451
12              Hermitage  47.042525  8.349718
13              Hergiswil  46.984481  8.312452
14       Isleten-Isenthal  46.919887  8.595783
15          Kastanienbaum  47.008001  8.340064
16         Kehrsiten Dorf  47.000364  8.365740
17              Küssnacht  47.080043  8.438873
18    Luzern Schweizerhof  47.053637  8.309968
19                 Meggen  47.044682  8.379297
20             Meggenhorn  47.033720  8.354259
21          Merlischachen  47.063919  8.407389
22                  Rütli  46.970366  8.593277
23                Seeburg  47.045672  8.344705
24                Sisikon  46.948196  8.619173
25              Stansstad  46.980653  8.336181
26            Tellsplatte  46.934116  8.612565
27                  Treib  46.987316  8.585683
28              Tribschen  47.042042  8.330726
29      Verkehrshaus-Lido  47.051116  8.334813
30                Vitznau  47.009376  8.482287
31                 Weggis  47.031530  8.433249

In [16]:
itinerary[itinerary['previous_stat'] != ""]

                                   previous_stat          next_stat       IN  \
course_nr station
23        Beckenried                     Vitznau                end   2398.0
          Hertenstein          Verkehrshaus-Lido             Weggis      568
          Luzern Bahnhofquai               start  Verkehrshaus-Lido  23563.0
          Verkehrshaus-Lido   Luzern Bahnhofquai        Hertenstein   1565.0
          Vitznau                         Weggis         Beckenried   3295.0
          Weggis                     Hertenstein            Vitznau   2730.0
25        Beckenried                     Vitznau                end   1295.0
          Hertenstein          Verkehrshaus-Lido             Weggis      359
          Luzern Bahnhofquai               start  Verkehrshaus-Lido  13825.0
          Verkehrshaus-Lido   Luzern Bahnhofquai        Hertenstein   1348.0
          Vitznau                         Weggis         Beckenried   2004.0
          Weggis                     Hertenstein            Vitznau   1745.0
27        Beckenried                     Vitznau                end   1132.0
          Hertenstein          Verkehrshaus-Lido             Weggis      465
          Luzern Bahnhofquai               start  Verkehrshaus-Lido  18416.0
          Verkehrshaus-Lido   Luzern Bahnhofquai        Hertenstein   1740.0
          Vitznau                         Weggis         Beckenried   2087.0
          Weggis                     Hertenstein            Vitznau   1523.0
425       Beckenried                       start             Gersau     0
          Brunnen                          Treib                end     0
          Gersau                      Beckenried              Treib     0
          Treib                           Gersau            Brunnen     0
427       Brunnen                          Treib                end     0
          Treib                            start            Brunnen      146

                                 OUT
course_nr station
23        Beckenried          5350.0
          Hertenstein         1381.0
          Luzern Bahnhofquai       8
          Verkehrshaus-Lido   1746.0
          Vitznau             5458.0
          Weggis              8401.0
25        Beckenried          3115.0
          Hertenstein            833
          Luzern Bahnhofquai    0
          Verkehrshaus-Lido      918
          Vitznau             3379.0
          Weggis              4862.0
27        Beckenried          2715.0
          Hertenstein         1217.0
          Luzern Bahnhofquai      27
          Verkehrshaus-Lido   1319.0
          Vitznau             4531.0
          Weggis              7912.0
425       Beckenried            0
          Brunnen               0
          Gersau                0
          Treib                 0
427       Brunnen                534
          Treib                  222

In [17]:
# add column to main df: 'station_long', 'station_lat', 'next_long', 'next_lat'
#get rid of column missing data 
itinerary = itinerary[(itinerary['previous_stat'] != "") & (itinerary['IN'].astype(float) != 0.0)]

itinerary['station_long'] = ""
itinerary['station_lat'] = ""
itinerary['next_long'] = ""
itinerary['next_lat'] = ""

for i, r in itinerary.iterrows():
  itinerary['station_long'][i] = str(coord['Long'][coord['Station'] == i[1]].values).strip('[]')
  itinerary['station_lat'][i] = str(coord['Lat'][coord['Station'] == i[1]].values).strip('[]')
  itinerary['next_long'][i] = str(coord['Long'][coord['Station'] == r['next_stat']].values).strip('[]')
  itinerary['next_lat'][i] = str(coord['Lat'][coord['Station'] == r['next_stat']].values).strip('[]')

itinerary

<ipython-input-17-53fade88b12c>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  itinerary['station_long'] = ""
<ipython-input-17-53fade88b12c>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  itinerary['station_lat'] = ""
<ipython-input-17-53fade88b12c>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  itinerary['next_long'] = ""
<ipython-input-17-53fade88b12c>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  itinerary['next_lat'] = ""
<ipython-input-17-53fade88b12c>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  itinerary['station_long'][i] = str(coord['Long'][coord['Station'] == i[1]].values).strip('[]')
<ipython-input-17-53fade88b12c>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  itinerary['station_lat'][i] = str(coord['Lat'][coord['Station'] == i[1]].values).strip('[]')
<ipython-input-17-53fade88b12c>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  itinerary['next_long'][i] = str(coord['Long'][coord['Station'] == r['next_stat']].values).strip('[]')
<ipython-input-17-53fade88b12c>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  itinerary['next_lat'][i] = str(coord['Lat'][coord['Station'] == r['next_stat']].values).strip('[]')

                                   previous_stat          next_stat       IN  \
course_nr station
23        Beckenried                     Vitznau                end   2398.0
          Hertenstein          Verkehrshaus-Lido             Weggis      568
          Luzern Bahnhofquai               start  Verkehrshaus-Lido  23563.0
          Verkehrshaus-Lido   Luzern Bahnhofquai        Hertenstein   1565.0
          Vitznau                         Weggis         Beckenried   3295.0
          Weggis                     Hertenstein            Vitznau   2730.0
25        Beckenried                     Vitznau                end   1295.0
          Hertenstein          Verkehrshaus-Lido             Weggis      359
          Luzern Bahnhofquai               start  Verkehrshaus-Lido  13825.0
          Verkehrshaus-Lido   Luzern Bahnhofquai        Hertenstein   1348.0
          Vitznau                         Weggis         Beckenried   2004.0
          Weggis                     Hertenstein            Vitznau   1745.0
27        Beckenried                     Vitznau                end   1132.0
          Hertenstein          Verkehrshaus-Lido             Weggis      465
          Luzern Bahnhofquai               start  Verkehrshaus-Lido  18416.0
          Verkehrshaus-Lido   Luzern Bahnhofquai        Hertenstein   1740.0
          Vitznau                         Weggis         Beckenried   2087.0
          Weggis                     Hertenstein            Vitznau   1523.0
427       Treib                            start            Brunnen      146

                                 OUT station_long station_lat    next_long  \
course_nr station
23        Beckenried          5350.0  46.96716954  8.47542071
          Hertenstein         1381.0   47.0269156  8.40345136  47.03153029
          Luzern Bahnhofquai       8  47.05130456  8.31023962  47.05111551
          Verkehrshaus-Lido   1746.0  47.05111551  8.33481258   47.0269156
          Vitznau             5458.0  47.00937644  8.48228721  46.96716954
          Weggis              8401.0  47.03153029  8.43324936  47.00937644
25        Beckenried          3115.0  46.96716954  8.47542071
          Hertenstein            833   47.0269156  8.40345136  47.03153029
          Luzern Bahnhofquai    0     47.05130456  8.31023962  47.05111551
          Verkehrshaus-Lido      918  47.05111551  8.33481258   47.0269156
          Vitznau             3379.0  47.00937644  8.48228721  46.96716954
          Weggis              4862.0  47.03153029  8.43324936  47.00937644
27        Beckenried          2715.0  46.96716954  8.47542071
          Hertenstein         1217.0   47.0269156  8.40345136  47.03153029
          Luzern Bahnhofquai      27  47.05130456  8.31023962  47.05111551
          Verkehrshaus-Lido   1319.0  47.05111551  8.33481258   47.0269156
          Vitznau             4531.0  47.00937644  8.48228721  46.96716954
          Weggis              7912.0  47.03153029  8.43324936  47.00937644
427       Treib                  222  46.98731648  8.58568309  46.99333813

                                next_lat
course_nr station
23        Beckenried
          Hertenstein         8.43324936
          Luzern Bahnhofquai  8.33481258
          Verkehrshaus-Lido   8.40345136
          Vitznau             8.47542071
          Weggis              8.48228721
25        Beckenried
          Hertenstein         8.43324936
          Luzern Bahnhofquai  8.33481258
          Verkehrshaus-Lido   8.40345136
          Vitznau             8.47542071
          Weggis              8.48228721
27        Beckenried
          Hertenstein         8.43324936
          Luzern Bahnhofquai  8.33481258
          Verkehrshaus-Lido   8.40345136
          Vitznau             8.47542071
          Weggis              8.48228721
427       Treib               8.60526523

In [18]:
#reset index and ad column 'load'

itinerary_re_i = itinerary.reset_index(level=[0,1])
itinerary_re_i["load"] = 0
itinerary_re_i

,course_nr,station,previous_stat,next_stat,IN,OUT,station_long,station_lat,next_long,next_lat,load
0,23,Beckenried,Vitznau,end,2398.0,5350.0,46.96716954,8.47542071,,,0
1,23,Hertenstein,Verkehrshaus-Lido,Weggis,568,1381.0,47.0269156,8.40345136,47.03153029,8.43324936,0
2,23,Luzern Bahnhofquai,start,Verkehrshaus-Lido,23563.0,8,47.05130456,8.31023962,47.05111551,8.33481258,0
3,23,Verkehrshaus-Lido,Luzern Bahnhofquai,Hertenstein,1565.0,1746.0,47.05111551,8.33481258,47.0269156,8.40345136,0
4,23,Vitznau,Weggis,Beckenried,3295.0,5458.0,47.00937644,8.48228721,46.96716954,8.47542071,0
5,23,Weggis,Hertenstein,Vitznau,2730.0,8401.0,47.03153029,8.43324936,47.00937644,8.48228721,0
6,25,Beckenried,Vitznau,end,1295.0,3115.0,46.96716954,8.47542071,,,0
7,25,Hertenstein,Verkehrshaus-Lido,Weggis,359,833,47.0269156,8.40345136,47.03153029,8.43324936,0
8,25,Luzern Bahnhofquai,start,Verkehrshaus-Lido,13825.0,0,47.05130456,8.31023962,47.05111551,8.33481258,0
9,25,Verkehrshaus-Lido,Luzern Bahnhofquai,Hertenstein,1348.0,918,47.05111551,8.33481258,47.0269156,8.40345136,0
10,25,Vitznau,Weggis,Beckenried,2004.0,3379.0,47.00937644,8.48228721,46.96716954,8.47542071,0
11,25,Weggis,Hertenstein,Vitznau,1745.0,4862.0,47.03153029,8.43324936,47.00937644,8.48228721,0
12,27,Beckenried,Vitznau,end,1132.0,2715.0,46.96716954,8.47542071,,,0
13,27,Hertenstein,Verkehrshaus-Lido,Weggis,465,1217.0,47.0269156,8.40345136,47.03153029,8.43324936,0
14,27,Luzern Bahnhofquai,start,Verkehrshaus-Lido,18416.0,27,47.05130456,8.31023962,47.05111551,8.33481258,0
15,27,Verkehrshaus-Lido,Luzern Bahnhofquai,Hertenstein,1740.0,1319.0,47.05111551,8.33481258,47.0269156,8.40345136,0
16,27,Vitznau,Weggis,Beckenried,2087.0,4531.0,47.00937644,8.48228721,46.96716954,8.47542071,0
17,27,Weggis,Hertenstein,Vitznau,1523.0,7912.0,47.03153029,8.43324936,47.00937644,8.48228721,0
18,427,Treib,start,Brunnen,146,222,46.98731648,8.58568309,46.99333813,8.60526523,0

In [19]:
#calculate passenger load for all starting stations; load = IN

for i, r in itinerary_re_i[itinerary_re_i['previous_stat'] == "start"].iterrows():
 itinerary_re_i['load'][i] = int(itinerary_re_i['IN'][i])

itinerary_re_i

<ipython-input-19-e7adfb2c7c31>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  itinerary_re_i['load'][i] = int(itinerary_re_i['IN'][i])

,course_nr,station,previous_stat,next_stat,IN,OUT,station_long,station_lat,next_long,next_lat,load
0,23,Beckenried,Vitznau,end,2398.0,5350.0,46.96716954,8.47542071,,,0
1,23,Hertenstein,Verkehrshaus-Lido,Weggis,568,1381.0,47.0269156,8.40345136,47.03153029,8.43324936,0
2,23,Luzern Bahnhofquai,start,Verkehrshaus-Lido,23563.0,8,47.05130456,8.31023962,47.05111551,8.33481258,23563
3,23,Verkehrshaus-Lido,Luzern Bahnhofquai,Hertenstein,1565.0,1746.0,47.05111551,8.33481258,47.0269156,8.40345136,0
4,23,Vitznau,Weggis,Beckenried,3295.0,5458.0,47.00937644,8.48228721,46.96716954,8.47542071,0
5,23,Weggis,Hertenstein,Vitznau,2730.0,8401.0,47.03153029,8.43324936,47.00937644,8.48228721,0
6,25,Beckenried,Vitznau,end,1295.0,3115.0,46.96716954,8.47542071,,,0
7,25,Hertenstein,Verkehrshaus-Lido,Weggis,359,833,47.0269156,8.40345136,47.03153029,8.43324936,0
8,25,Luzern Bahnhofquai,start,Verkehrshaus-Lido,13825.0,0,47.05130456,8.31023962,47.05111551,8.33481258,13825
9,25,Verkehrshaus-Lido,Luzern Bahnhofquai,Hertenstein,1348.0,918,47.05111551,8.33481258,47.0269156,8.40345136,0
10,25,Vitznau,Weggis,Beckenried,2004.0,3379.0,47.00937644,8.48228721,46.96716954,8.47542071,0
11,25,Weggis,Hertenstein,Vitznau,1745.0,4862.0,47.03153029,8.43324936,47.00937644,8.48228721,0
12,27,Beckenried,Vitznau,end,1132.0,2715.0,46.96716954,8.47542071,,,0
13,27,Hertenstein,Verkehrshaus-Lido,Weggis,465,1217.0,47.0269156,8.40345136,47.03153029,8.43324936,0
14,27,Luzern Bahnhofquai,start,Verkehrshaus-Lido,18416.0,27,47.05130456,8.31023962,47.05111551,8.33481258,18416
15,27,Verkehrshaus-Lido,Luzern Bahnhofquai,Hertenstein,1740.0,1319.0,47.05111551,8.33481258,47.0269156,8.40345136,0
16,27,Vitznau,Weggis,Beckenried,2087.0,4531.0,47.00937644,8.48228721,46.96716954,8.47542071,0
17,27,Weggis,Hertenstein,Vitznau,1523.0,7912.0,47.03153029,8.43324936,47.00937644,8.48228721,0
18,427,Treib,start,Brunnen,146,222,46.98731648,8.58568309,46.99333813,8.60526523,146

In [20]:
#calculate passenger load for all NON starting stations; load = 'previous load' + (IN - OUT)
#because df order is not correct: innerloop breaks if 0 in prev_load, outerloop stops if no 0 in load

while 0 in itinerary_re_i['load'].values:
  print(0 in itinerary_re_i['load'])
  print('_' * 60)
  for i, r in itinerary_re_i[itinerary_re_i['previous_stat'] != "start"].iterrows():
      prev_load = itinerary_re_i[(itinerary_re_i['course_nr'] == r['course_nr']) & (itinerary_re_i['station'] == r['previous_stat'])]['load'] #get load value of previous station
      if prev_load.values != 0:
        itinerary_re_i['load'][i] = (int(prev_load.values) + (int(r['IN']) - int(r['OUT'])))
        print(f'calculated load {itinerary_re_i["load"][i]}')

True
____________________________________________________________
calculated load 23382
calculated load 14255
calculated load 18837
True
____________________________________________________________
calculated load 22569
calculated load 23382
calculated load 16898
calculated load 13781
calculated load 14255
calculated load 10664
calculated load 18085
calculated load 18837
calculated load 11696
True
____________________________________________________________
calculated load 22569
calculated load 23382
calculated load 14735
calculated load 16898
calculated load 13781
calculated load 14255
calculated load 9289
calculated load 10664
calculated load 18085
calculated load 18837
calculated load 9252
calculated load 11696
True
____________________________________________________________
calculated load 11783
calculated load 22569
calculated load 23382
calculated load 14735
calculated load 16898
calculated load 7469
calculated load 13781
calculated load 14255
calculated load 9289
calculated load 10664
calculated load 7669
calculated load 18085
calculated load 18837
calculated load 9252
calculated load 11696

<ipython-input-20-302153752549>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  itinerary_re_i['load'][i] = (int(prev_load.values) + (int(r['IN']) - int(r['OUT'])))

In [21]:
itinerary_re_i

,course_nr,station,previous_stat,next_stat,IN,OUT,station_long,station_lat,next_long,next_lat,load
0,23,Beckenried,Vitznau,end,2398.0,5350.0,46.96716954,8.47542071,,,11783
1,23,Hertenstein,Verkehrshaus-Lido,Weggis,568,1381.0,47.0269156,8.40345136,47.03153029,8.43324936,22569
2,23,Luzern Bahnhofquai,start,Verkehrshaus-Lido,23563.0,8,47.05130456,8.31023962,47.05111551,8.33481258,23563
3,23,Verkehrshaus-Lido,Luzern Bahnhofquai,Hertenstein,1565.0,1746.0,47.05111551,8.33481258,47.0269156,8.40345136,23382
4,23,Vitznau,Weggis,Beckenried,3295.0,5458.0,47.00937644,8.48228721,46.96716954,8.47542071,14735
5,23,Weggis,Hertenstein,Vitznau,2730.0,8401.0,47.03153029,8.43324936,47.00937644,8.48228721,16898
6,25,Beckenried,Vitznau,end,1295.0,3115.0,46.96716954,8.47542071,,,7469
7,25,Hertenstein,Verkehrshaus-Lido,Weggis,359,833,47.0269156,8.40345136,47.03153029,8.43324936,13781
8,25,Luzern Bahnhofquai,start,Verkehrshaus-Lido,13825.0,0,47.05130456,8.31023962,47.05111551,8.33481258,13825
9,25,Verkehrshaus-Lido,Luzern Bahnhofquai,Hertenstein,1348.0,918,47.05111551,8.33481258,47.0269156,8.40345136,14255
10,25,Vitznau,Weggis,Beckenried,2004.0,3379.0,47.00937644,8.48228721,46.96716954,8.47542071,9289
11,25,Weggis,Hertenstein,Vitznau,1745.0,4862.0,47.03153029,8.43324936,47.00937644,8.48228721,10664
12,27,Beckenried,Vitznau,end,1132.0,2715.0,46.96716954,8.47542071,,,7669
13,27,Hertenstein,Verkehrshaus-Lido,Weggis,465,1217.0,47.0269156,8.40345136,47.03153029,8.43324936,18085
14,27,Luzern Bahnhofquai,start,Verkehrshaus-Lido,18416.0,27,47.05130456,8.31023962,47.05111551,8.33481258,18416
15,27,Verkehrshaus-Lido,Luzern Bahnhofquai,Hertenstein,1740.0,1319.0,47.05111551,8.33481258,47.0269156,8.40345136,18837
16,27,Vitznau,Weggis,Beckenried,2087.0,4531.0,47.00937644,8.48228721,46.96716954,8.47542071,9252
17,27,Weggis,Hertenstein,Vitznau,1523.0,7912.0,47.03153029,8.43324936,47.00937644,8.48228721,11696
18,427,Treib,start,Brunnen,146,222,46.98731648,8.58568309,46.99333813,8.60526523,146

In [23]:
#save data on drive

itinerary_re_i.to_csv('/content/drive/My Drive/Colab Notebooks/geo_data/itinerary_df.csv')